apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aios-operator
  labels:
    app.kubernetes.io/name: aios-operator
    app.kubernetes.io/part-of: aios
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aios-operator
subjects:
  - kind: ServiceAccount
    name: aios-operator
    namespace: aios
