---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: aios-search-qdrant
  labels:
    app: {{ .Release.Name }}
spec:
  itemPath: "vaults/${OP_VAULT}/items/${OP_ITEM_AIOS_SEARCH_QDRANT}"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: aios-search-api-key
  labels:
    app: {{ .Release.Name }}
spec:
  itemPath: "vaults/${OP_VAULT}/items/${OP_ITEM_AIOS_SEARCH_API_KEY}"
