import { describe, it, expect, vi, beforeEach } from "vitest";
import { runDeliver } from "./deliver.js";
import type { TaskConfig } from "../types.js";

const config: TaskConfig = {
  taskId: "task-1",
  taskType: "code",
  prompt: "Fix the bug in authentication",
  repo: "owner/repo",
  issueNumber: 42,
  branch: "fix-branch",
  slackChannel: "C123",
  memoryUrl: "http://memory:8080",
  searchUrl: "http://search:8080",
  workspace: "/workspace",
  model: "claude-sonnet-4-6",
  maxTokens: 16384,
};

const mockGithub = {
  createPR: vi.fn(),
  updateIssueLabel: vi.fn(),
};

const mockFabric = {
  run: vi.fn(),
};

const mockMemory = {
  storeMemory: vi.fn(),
};

const mockSlack = {
  postToThread: vi.fn().mockResolvedValue(undefined),
  postTaskCompleted: vi.fn().mockResolvedValue(undefined),
};

describe("runDeliver", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockGithub.createPR.mockResolvedValue("https://github.com/owner/repo/pull/99");
    mockGithub.updateIssueLabel.mockResolvedValue(undefined);
    mockFabric.run.mockResolvedValue({
      exitCode: 0,
      stdout: "## Summary\nFixed auth bug\n\n---\n_Generated by AIOS_",
      stderr: "",
    });
    mockMemory.storeMemory.mockResolvedValue(undefined);
  });

  it("creates a PR with fabric-generated description", async () => {
    const result = await runDeliver(
      config,
      mockGithub as any,
      mockFabric as any,
      mockMemory as any,
      mockSlack as any,
      "thread-ts",
      "the plan",
      "implementation summary",
    );

    expect(result.prUrl).toBe("https://github.com/owner/repo/pull/99");
    expect(mockGithub.createPR).toHaveBeenCalledWith(
      "[AIOS] Fix the bug in authentication",
      expect.stringContaining("Fixed auth bug"),
    );
  });

  it("falls back to simple PR body when fabric fails", async () => {
    mockFabric.run.mockResolvedValue({ exitCode: 1, stdout: "", stderr: "error" });

    const result = await runDeliver(
      config,
      mockGithub as any,
      mockFabric as any,
      mockMemory as any,
      mockSlack as any,
      "thread-ts",
      "the plan",
      "implementation summary",
    );

    expect(result.prUrl).toBe("https://github.com/owner/repo/pull/99");
    expect(mockGithub.createPR).toHaveBeenCalledWith(
      expect.any(String),
      expect.stringContaining("implementation summary"),
    );
  });

  it("updates issue label when issue number is set", async () => {
    await runDeliver(
      config,
      mockGithub as any,
      mockFabric as any,
      mockMemory as any,
      mockSlack as any,
      "thread-ts",
      "plan",
      "summary",
    );

    expect(mockGithub.updateIssueLabel).toHaveBeenCalledWith(42, "aios:delivered");
  });

  it("skips issue label update when no issue number", async () => {
    const configNoIssue = { ...config, issueNumber: undefined };

    await runDeliver(
      configNoIssue,
      mockGithub as any,
      mockFabric as any,
      mockMemory as any,
      mockSlack as any,
      "thread-ts",
      "plan",
      "summary",
    );

    expect(mockGithub.updateIssueLabel).not.toHaveBeenCalled();
  });

  it("stores delivery in memory", async () => {
    await runDeliver(
      config,
      mockGithub as any,
      mockFabric as any,
      mockMemory as any,
      mockSlack as any,
      "thread-ts",
      "plan",
      "summary",
    );

    expect(mockMemory.storeMemory).toHaveBeenCalledWith(
      "deliver:task-1",
      expect.any(String),
      expect.objectContaining({
        taskId: "task-1",
        prUrl: "https://github.com/owner/repo/pull/99",
        type: "delivery",
      }),
    );
  });

  it("notifies Slack on completion", async () => {
    await runDeliver(
      config,
      mockGithub as any,
      mockFabric as any,
      mockMemory as any,
      mockSlack as any,
      "thread-ts",
      "plan",
      "summary",
    );

    expect(mockSlack.postTaskCompleted).toHaveBeenCalledWith(
      "thread-ts",
      "task-1",
      "https://github.com/owner/repo/pull/99",
    );
  });

  it("truncates long prompts in PR title", async () => {
    const longConfig = {
      ...config,
      prompt: "A".repeat(100),
    };

    await runDeliver(
      longConfig,
      mockGithub as any,
      mockFabric as any,
      mockMemory as any,
      mockSlack as any,
      "thread-ts",
      "plan",
      "summary",
    );

    const prTitle = mockGithub.createPR.mock.calls[0][0];
    expect(prTitle).toContain("...");
    expect(prTitle.length).toBeLessThan(80);
  });
});
