import type { TaskConfig } from "../types.js";
import type { FabricRunner } from "../fabric.js";
import type { GitHubClient } from "../github.js";
import type { SlackNotifier } from "../slack.js";
import type { MemoryClient } from "../memory.js";

export interface DeliverResult {
  prUrl: string;
}

/**
 * Deliver stage: generates PR description, creates PR, updates issue, notifies Slack.
 */
export async function runDeliver(
  config: TaskConfig,
  github: GitHubClient,
  fabric: FabricRunner,
  memory: MemoryClient,
  slack: SlackNotifier,
  threadTs: string,
  plan: string,
  implementSummary: string,
): Promise<DeliverResult> {
  await slack.postToThread(
    config.slackChannel,
    threadTs,
    `:truck: Preparing delivery...`,
  );

  // Generate PR description with fabric
  const prInput = [
    "## Task",
    config.prompt,
    "",
    "## Plan",
    plan,
    "",
    "## Implementation Summary",
    implementSummary,
  ].join("\n");

  const prDescResult = await fabric.run("pr_description", prInput);

  const prBody =
    prDescResult.exitCode === 0
      ? prDescResult.stdout
      : `## Summary\n\n${implementSummary}\n\n---\n_Generated by AIOS_`;

  // Create PR
  const prTitle = `[AIOS] ${config.prompt.slice(0, 60)}${config.prompt.length > 60 ? "..." : ""}`;
  const prUrl = await github.createPR(prTitle, prBody);

  // Update issue label and close if applicable
  if (config.issueNumber) {
    await github.updateIssueLabel(config.issueNumber, "aios:delivered");
  }

  // Store delivery in memory
  await memory.storeMemory(`deliver:${config.taskId}`, prBody, {
    taskId: config.taskId,
    prUrl,
    type: "delivery",
  });

  // Notify Slack with completion
  await slack.postTaskCompleted(threadTs, config.taskId, prUrl);

  return { prUrl };
}
